// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfldrylxrmwleqjcxxdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmbGRyeWx4cm13bGVxamN4eGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NTA0NTUsImV4cCI6MjA4ODMyNjQ1NX0.hD9ZLQ8Xl0fK6ACD6aMoWkqKfeNuU2eqH9ToJ3eGTss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});